/**
 * Ambient Module Declarations for Federated Micro-Frontend Remotes.
 * Auto-generated by scripts/generate-remotes-dts.js from remotes.manifest.json.
 * DO NOT EDIT DIRECTLY.
 */

declare module "demoService/App" {
  import { ComponentType } from "react";
  const Component: ComponentType<any>;
  export default Component;
}

declare module "demoService/MfeDevWidget" {
  import { ComponentType } from "react";
  export interface MfeDevWidgetProps {
    title?: string;
  }
  const MfeDevWidget: ComponentType<MfeDevWidgetProps>;
  export default MfeDevWidget;
}
