import React from "react";

/**
 * Manifest-Driven Remote Routes Registry.
 * Auto-generated by scripts/generate-remotes-dts.js from remotes.manifest.json.
 * DO NOT EDIT DIRECTLY.
 */
export const remoteRoutes = [
  {
    name: "marketingMfe",
    path: "/landing/*",
    Component: React.lazy(() => import("marketingMfe/App")),
    framework: "react",
  },
  {
    name: "authMfe",
    path: "/auth/*",
    Component: React.lazy(() => import("authMfe/App")),
    framework: "react",
  },
];
