/**
 * Ambient Module Declarations for Federated Micro-Frontend Remotes.
 * Auto-generated by scripts/generate-remotes-dts.js from remotes.manifest.json.
 * DO NOT EDIT DIRECTLY.
 */

declare module "marketingMfe/App" {
  import { ComponentType } from "react";
  const Component: ComponentType<any>;
  export default Component;
}

declare module "authMfe/App" {
  import { ComponentType } from "react";
  const Component: ComponentType<any>;
  export default Component;
}
